export const visionAnalysisCopy = {
  analyzeImage: "分析图片",
  reanalyzeImage: "重新分析",
  viewSuggestions: "查看建议",
  analyzing: "分析中",
  pending: "等待分析",
  completed: "分析完成",
  failed: "分析失败",
  title: "视觉分析建议",
  description:
    "推荐结果由配置的视觉服务根据原图生成，只作为建议展示，不会自动覆盖正式元数据。",
  privacyNotice: "点击分析后，原图会发送到当前配置的云端视觉服务。请确认你拥有这张图片的使用权。",
  noSuggestion: "当前没有可审核的分析建议。",
  startFailed: "分析任务创建失败。",
  confirmFailed: "建议采纳失败。",
  rejectFailed: "建议拒绝失败。",
  accepted: "建议已采纳。",
  rejected: "建议已拒绝。",
  started: "分析任务已开始。",
  timeout: "等待时间较长，可以稍后重新检查状态。",
  checkStatus: "重新检查状态",
  acceptSelected: "采纳选中字段",
  rejectSuggestion: "拒绝建议",
  selectField: "采纳",
  currentValue: "当前正式值",
  suggestedValue: "建议值",
  finalValue: "最终采纳值",
  empty: "未填写",
  oldSuggestionKept: "重新分析失败，上一次建议仍保留。",
  fieldLabels: {
    shot_type: "景别",
    view_angle: "视角",
    expression: "表情",
    custom_expression: "自定义表情",
    pose_type: "姿势",
    custom_pose: "自定义姿势",
    tags: "标签",
    description: "描述",
    is_identity_anchor: "身份基准图",
    shot_scale: "景别",
    camera_position: "机位",
    custom_camera_position: "自定义机位",
    view_direction: "视向",
    custom_view_direction: "自定义视向",
    composition_type: "构图",
    custom_composition: "自定义构图",
    is_spatial_anchor: "空间结构基准图",
    is_empty_plate: "空镜"
  } as Record<string, string>
};
