import type { MissingItem, ReadinessStatus } from "./types";

export const shotCopy = {
  title: "镜头工作台",
  description: "按顺序组织镜头，并绑定场景、角色和参考图资产。",
  globalGuideTitle: "请先选择一个项目",
  globalGuideDescription: "镜头工作台按项目管理，不会自动猜测最近项目。",
  backToProject: "返回项目",
  newShot: "新建镜头",
  saveShot: "保存镜头",
  creating: "正在创建",
  saving: "正在保存",
  deleted: "镜头已删除",
  duplicated: "镜头已复制",
  moved: "镜头顺序已更新",
  loadFailed: "镜头数据加载失败，请稍后重试。",
  scenesLoadFailed: "场景列表加载失败，请稍后重试。",
  charactersLoadFailed: "角色列表加载失败，请稍后重试。",
  statesLoadFailed: "场景状态加载失败，请稍后重试。",
  noScenes: "当前项目还没有场景。",
  noCharacters: "当前项目还没有角色。",
  noSceneStates: "该场景还没有场景状态。",
  loadingOptions: "正在加载选项...",
  saveFailed: "镜头保存失败。",
  deleteFailed: "镜头删除失败。",
  emptyTitle: "当前项目还没有镜头",
  emptyDescription: "创建第一个镜头后，可以继续选择场景状态、添加角色并绑定参考图。",
  deleteShot: "删除镜头",
  deleteShotDescription: (name: string) =>
    `确定删除镜头「${name}」吗？这会删除本镜头内的角色绑定和参考图绑定，但不会删除角色库、场景库或原始媒体。`,
  deleteShotCharacter: "移除镜头角色",
  deleteShotCharacterDescription: (name: string) =>
    `确定从当前镜头移除「${name}」吗？与该镜头角色明确关联的人物参考图绑定会一并移除，角色库资产不会被删除。`,
  deleteShotReference: "移除参考图绑定",
  deleteShotReferenceDescription:
    "确定移除这条参考图绑定吗？原始参考图和媒体文件不会被删除。",
  sceneReferenceClearWarning:
    "切换或清空场景状态会移除当前镜头中不兼容的场景参考图绑定，是否继续？",
  noSceneReferenceWarning: "请先为镜头选择场景状态。",
  lookMismatchWarning: "该参考图所属造型与镜头角色当前造型不一致，可以继续作为身份或表演参考。",
  sections: {
    list: "镜头列表",
    basic: "镜头信息",
    scene: "场景绑定",
    camera: "摄影参数",
    characters: "镜头角色",
    characterRefs: "人物参考",
    sceneRefs: "场景参考",
    selectedRefs: "已绑定"
  },
  fields: {
    name: "镜头名称",
    visualDescription: "画面描述",
    storyDescription: "剧情说明",
    dialogue: "对白",
    actionSummary: "动作摘要",
    duration: "时长（秒）",
    scene: "场景",
    sceneState: "场景状态",
    shotScale: "景别",
    cameraHeight: "机位高度",
    cameraAngle: "拍摄角度",
    composition: "构图",
    cameraMovement: "镜头运动",
    focalSubject: "焦点主体",
    mood: "情绪氛围",
    notes: "备注",
    character: "角色",
    look: "造型",
    action: "动作",
    expression: "表情",
    position: "位置",
    primarySubject: "主主体",
    purpose: "用途"
  },
  readiness: {
    draft: "草稿",
    basic_ready: "基本完成",
    asset_ready: "资产就绪"
  } satisfies Record<ReadinessStatus, string>,
  missing: {
    visual_description: "缺少画面描述",
    scene: "缺少场景",
    scene_state: "缺少场景状态",
    characters: "缺少镜头角色",
    primary_subject: "缺少主主体",
    character_references: "缺少人物参考图",
    scene_references: "缺少场景参考图"
  } satisfies Record<MissingItem, string>,
  purposes: {
    identity: "身份",
    appearance: "外观",
    expression: "表情",
    pose: "姿势",
    framing: "构图",
    environment: "环境",
    spatial: "空间",
    composition: "构图",
    lighting: "光线",
    camera_reference: "机位",
    general: "通用"
  },
  options: {
    unknown: "未指定",
    extreme_wide: "大远景",
    wide: "远景",
    full: "全景",
    medium_wide: "中远景",
    medium: "中景",
    medium_close: "中近景",
    close: "近景",
    close_up: "特写",
    extreme_close_up: "大特写",
    eye_level: "平视",
    ground: "贴地",
    low: "低机位",
    high: "高机位",
    overhead: "俯拍",
    aerial: "航拍",
    custom: "自定义",
    front: "正面",
    back: "背面",
    left_profile: "左侧面",
    right_profile: "右侧面",
    left_three_quarter: "左前三分之二",
    right_three_quarter: "右前三分之二",
    top_down: "顶视",
    dutch_angle: "倾斜构图",
    pov: "主观视角",
    over_the_shoulder: "过肩",
    centered: "居中",
    symmetrical: "对称",
    rule_of_thirds: "三分法",
    leading_lines: "引导线",
    frame_within_frame: "框中框",
    layered: "层次构图",
    negative_space: "留白",
    close_blocking: "近距离调度",
    static: "固定",
    push_in: "推进",
    pull_out: "拉远",
    pan_left: "左摇",
    pan_right: "右摇",
    tilt_up: "上摇",
    tilt_down: "下摇",
    tracking: "跟拍",
    orbit: "环绕",
    handheld: "手持",
    crane: "升降",
    zoom_in: "变焦推进",
    zoom_out: "变焦拉远"
  }
};

export const shotRecommendationCopy = {
  tabs: {
    smart: "智能推荐",
    character: "人物参考",
    scene: "场景参考",
    selected: "已选资产"
  },
  description: "推荐结果根据镜头参数和资产元数据进行规则匹配，不使用训练模型，也不会自动绑定。",
  loading: "正在计算推荐...",
  loadFailed: "推荐结果加载失败，手动绑定仍可继续使用。",
  retry: "重新计算",
  noShot: "请选择镜头后查看推荐。",
  noCharacters: "请先添加镜头角色。",
  noCharacterReferences: "该角色还没有可用参考图。",
  sceneStateRequired: "请先选择场景状态。",
  noSceneReferences: "该场景状态暂无可推荐参考图。",
  bind: "绑定",
  binding: "正在绑定",
  bound: "已绑定",
  boundOtherPurpose: "已绑定其他用途",
  score: (value: number) => `${value} 分`,
  groupLook: (value: string | null) => (value ? `造型：${value}` : "未指定造型"),
  sourceLook: (value: string) => `来源造型：${value}`,
  sourceState: (value: string) => `来源状态：${value}`,
  reasons: {
    look_exact_match: "造型一致",
    different_look: "不同造型",
    shot_scale_exact: "景别精确",
    shot_scale_close: "景别相近",
    view_angle_exact: "视角精确",
    view_angle_close: "视角相近",
    identity_anchor: "身份基准",
    primary_reference: "主图",
    expression_match: "表情匹配",
    pose_match: "姿势匹配",
    already_bound_other_purpose: "已绑其他用途",
    camera_position_exact: "机位精确",
    camera_position_close: "机位相近",
    view_direction_exact: "视向精确",
    view_direction_close: "视向相近",
    composition_exact: "构图匹配",
    spatial_anchor: "空间基准",
    empty_plate: "空镜",
    keyword_match: "关键词匹配"
  }
};
