import type {
  AnalysisStatus,
  CameraPosition,
  CompositionType,
  CrowdLevel,
  Lighting,
  SceneType,
  Season,
  ShotScale,
  TimeOfDay,
  ViewDirection,
  Weather
} from "./types";

export const sceneCopy = {
  title: "场景库",
  description: "管理当前项目中的场景、环境状态和空间参考图。",
  newScene: "新建场景",
  editScene: "编辑场景",
  deleteScene: "删除场景",
  newState: "新建状态",
  newFirstState: "新建第一套状态",
  editState: "编辑状态",
  deleteState: "删除状态",
  setDefaultState: "设为默认状态",
  defaultState: "默认状态",
  uploadReference: "上传参考图",
  editReference: "编辑元数据",
  deleteReference: "删除参考图",
  setPrimaryReference: "设为主图",
  setSpatialAnchor: "设为空间结构基准",
  unsetSpatialAnchor: "取消空间结构基准",
  markEmptyPlate: "设为空镜",
  unmarkEmptyPlate: "取消空镜",
  previewOriginal: "查看原图",
  backToProject: "返回项目",
  backToScenes: "返回场景库",
  emptyTitle: "当前项目还没有场景",
  emptyDescription: "创建场景并上传空间参考图，为后续镜头生成建立环境资产。",
  emptyStatesTitle: "当前场景还没有状态",
  emptyStatesDescription: "创建第一个场景状态，例如“白天晴天”或“夜晚暴雨”。",
  emptyReferencesTitle: "当前状态还没有参考图",
  emptyReferencesDescription: "上传真实空间参考图后，可以补充景别、机位、朝向和构图信息。",
  globalGuideTitle: "请先选择一个项目",
  globalGuideDescription: "场景库属于具体项目。打开项目后，可从项目内导航进入场景库。",
  loadFailed: "场景库加载失败，请稍后重试。",
  saveFailed: "场景信息保存失败。",
  deleteFailed: "删除失败，请稍后重试。",
  stateSaveFailed: "场景状态保存失败。",
  stateDeleteFailed: "场景状态删除失败，请稍后重试。",
  lastStateDeleteForbidden: "不能删除场景的最后一个状态。",
  referenceSaveFailed: "参考图元数据保存失败。",
  referenceDeleteFailed: "参考图删除失败，请稍后重试。",
  referenceActionFailed: "参考图状态更新失败，请稍后重试。",
  uploadFailed: "参考图上传失败，请检查文件格式和大小。",
  created: "场景已创建。",
  updated: "场景已更新。",
  deleted: "场景已删除。",
  stateCreated: "场景状态已创建。",
  stateUpdated: "场景状态已更新。",
  stateDeleted: "场景状态已删除。",
  defaultStateUpdated: "默认状态已更新。",
  referenceUploaded: "参考图已上传。",
  referenceUpdated: "参考图元数据已更新。",
  referenceDeleted: "参考图已删除。",
  primaryReferenceUpdated: "主图已更新。",
  spatialAnchorUpdated: "空间结构基准状态已更新。",
  emptyPlateUpdated: "空镜状态已更新。",
  noDescription: "暂无说明",
  noValue: "未填写",
  primaryReference: "主图",
  spatialAnchor: "空间结构基准",
  emptyPlate: "空镜",
  notFoundTitle: "场景不存在或已被删除",
  cancel: "取消",
  confirmDelete: "确认删除",
  save: "保存",
  saving: "正在保存",
  uploading: "正在上传",
  deleting: "正在删除",
  deleteSceneDescription: (name: string) =>
    `确定删除场景“${name}”吗？该场景下的全部状态、参考图和媒体文件记录都会一并删除。`,
  deleteStateDescription: (name: string) =>
    `确定删除状态“${name}”吗？该状态下的全部参考图都会删除；如果它是默认状态，后端会自动选择新的默认状态。`,
  deleteReferenceDescription: (name: string) =>
    `确定删除参考图“${name}”吗？原图和缩略图会在数据库删除成功后清理。`,
  fields: {
    name: "名称",
    sceneType: "场景类型",
    description: "说明",
    fixedEnvironment: "固定环境描述",
    spatialLayout: "空间布局描述",
    visualStyle: "视觉风格描述",
    promptEnvironment: "环境提示描述",
    notes: "备注",
    stateName: "状态名称",
    timeOfDay: "时间",
    weather: "天气",
    customWeather: "自定义天气",
    lighting: "灯光",
    customLighting: "自定义灯光",
    season: "季节",
    environmentCondition: "环境状态",
    crowdLevel: "人群密度",
    promptState: "状态提示描述",
    file: "参考图片",
    originalFilename: "原始文件名",
    imageSize: "图片尺寸",
    fileType: "文件类型",
    fileSize: "文件大小",
    shotScale: "景别",
    cameraPosition: "机位",
    customCameraPosition: "自定义机位",
    viewDirection: "朝向",
    customViewDirection: "自定义朝向",
    compositionType: "构图",
    customComposition: "自定义构图",
    referenceDescription: "参考图描述",
    tags: "标签",
    isPrimary: "主图状态",
    isSpatialAnchor: "空间结构基准状态",
    isEmptyPlate: "空镜状态"
  },
  placeholders: {
    name: "例如：集团办公楼外",
    fixedEnvironment: "描述不随时间、天气变化的地点特征，例如外墙、门厅、街道结构",
    spatialLayout: "描述入口、走廊、道路、家具或建筑之间的空间关系",
    visualStyle: "描述整体材质、色调和摄影质感",
    promptEnvironment: "供后续生成保持空间一致性的环境描述",
    stateName: "例如：夜晚暴雨·警车封锁",
    environmentCondition: "例如：地面湿润、门口拉起警戒线、室内烟雾弥漫",
    promptState: "供后续生成保持状态一致性的环境描述",
    referenceTags: "用逗号分隔，例如：正门, 雨夜, 空镜",
    referenceDescription: "补充这张图的可用信息",
    notes: "仅用于制作管理的内部备注"
  },
  sceneType: {
    interior: "室内",
    exterior: "室外",
    mixed: "内外混合",
    vehicle: "交通工具",
    virtual: "虚拟空间",
    other: "其他"
  } satisfies Record<SceneType, string>,
  timeOfDay: {
    dawn: "黎明",
    morning: "上午",
    noon: "正午",
    afternoon: "下午",
    dusk: "黄昏",
    night: "夜晚",
    late_night: "深夜",
    unknown: "未知"
  } satisfies Record<TimeOfDay, string>,
  weather: {
    clear: "晴朗",
    cloudy: "多云",
    overcast: "阴天",
    light_rain: "小雨",
    heavy_rain: "暴雨",
    storm: "风暴",
    snow: "雪",
    fog: "雾",
    indoor: "室内",
    custom: "自定义",
    unknown: "未知"
  } satisfies Record<Weather, string>,
  lighting: {
    natural_soft: "柔和自然光",
    natural_hard: "强烈自然光",
    warm_indoor: "暖色室内光",
    cool_indoor: "冷色室内光",
    neon: "霓虹光",
    low_key: "低调光",
    high_key: "高调光",
    backlight: "逆光",
    mixed: "混合光",
    custom: "自定义",
    unknown: "未知"
  } satisfies Record<Lighting, string>,
  season: {
    spring: "春季",
    summer: "夏季",
    autumn: "秋季",
    winter: "冬季",
    not_applicable: "不适用",
    unknown: "未知"
  } satisfies Record<Season, string>,
  crowdLevel: {
    empty: "无人",
    sparse: "稀少",
    normal: "正常",
    crowded: "拥挤",
    packed: "密集",
    unknown: "未知"
  } satisfies Record<CrowdLevel, string>,
  shotScale: {
    extreme_wide: "大远景",
    wide: "远景",
    full: "全景",
    medium_wide: "中远景",
    medium: "中景",
    close: "近景",
    detail: "细节",
    unknown: "未知"
  } satisfies Record<ShotScale, string>,
  cameraPosition: {
    eye_level: "平视",
    low_angle: "低机位",
    high_angle: "高机位",
    ground_level: "贴地",
    overhead: "俯拍",
    aerial: "航拍",
    doorway: "门口",
    corner: "角落",
    custom: "自定义",
    unknown: "未知"
  } satisfies Record<CameraPosition, string>,
  viewDirection: {
    front: "正面",
    left: "左侧",
    right: "右侧",
    back: "背面",
    diagonal_left: "左斜向",
    diagonal_right: "右斜向",
    inward: "向内",
    outward: "向外",
    custom: "自定义",
    unknown: "未知"
  } satisfies Record<ViewDirection, string>,
  compositionType: {
    centered: "居中",
    symmetrical: "对称",
    rule_of_thirds: "三分法",
    leading_lines: "引导线",
    frame_within_frame: "框中框",
    deep_focus: "深焦",
    layered: "层次构图",
    custom: "自定义",
    unknown: "未知"
  } satisfies Record<CompositionType, string>,
  analysisStatus: {
    not_analyzed: "尚未分析",
    pending: "分析中",
    completed: "分析完成",
    failed: "分析失败"
  } satisfies Record<AnalysisStatus, string>
};
