export const promptBuilderCopy = {
  title: "Prompt / 上下文草稿",
  description: "根据镜头人物、场景、状态和参考图生成可编辑草稿，不会自动保存或开始生成。",
  generate: "生成提示词草稿",
  generating: "正在生成...",
  regenerate: "重新生成草稿",
  loadFailed: "提示词草稿生成失败，不影响当前页面操作。",
  contextSummary: "镜头上下文",
  firstFramePrompt: "首帧 / 关键帧提示词",
  endFramePrompt: "尾帧提示词",
  motionPrompt: "视频运动提示词",
  negativePrompt: "反向提示词",
  cameraMotion: "镜头运动",
  warnings: "上下文提示",
  copy: "复制提示词",
  copied: "已复制",
  fillKeyframe: "填入关键帧提示词",
  fillVideo: "填入视频运动提示词",
  generateFromShot: "从镜头上下文生成",
  overwriteConfirm: "这会覆盖当前表单中的提示词草稿，是否继续？",
  keyframeFilled: "已填入关键帧提示词草稿，请检查后手动保存任务。",
  videoFilled: "已填入视频运动提示词草稿，请检查后手动保存任务。",
  noDraft: "还没有生成提示词草稿。",
  noWarnings: "当前没有明显缺失项。",
  safeNote: "仅生成草稿，不会修改镜头、任务或生成记录。"
};
