import type {
  AnalysisStatus,
  Expression,
  PoseType,
  RoleType,
  ShotType,
  ViewAngle
} from "./types";

export const characterCopy = {
  title: "角色库",
  description: "管理项目中的人物、造型和参考图元数据。",
  newCharacter: "新建角色",
  editCharacter: "编辑角色",
  deleteCharacter: "删除角色",
  newLook: "新建造型",
  newFirstLook: "新建第一套造型",
  editLook: "编辑造型",
  deleteLook: "删除造型",
  setDefaultLook: "设为默认造型",
  defaultLook: "默认造型",
  uploadReference: "上传参考图",
  editReference: "编辑元数据",
  deleteReference: "删除参考图",
  setPrimaryReference: "设为主图",
  setIdentityAnchor: "设为身份基准",
  unsetIdentityAnchor: "取消身份基准",
  previewOriginal: "查看原图",
  backToProject: "返回项目",
  backToCharacters: "返回角色库",
  emptyTitle: "当前项目还没有角色",
  emptyDescription: "先创建角色，再为角色补充造型和参考图。",
  emptyLooksTitle: "当前角色还没有造型",
  emptyLooksDescription: "创建第一套造型并上传定妆参考图。",
  emptyReferencesTitle: "当前造型还没有参考图",
  emptyReferencesDescription: "上传真实参考图后，可补充景别、视角、表情、姿势和标签。",
  loadFailed: "角色库加载失败，请稍后重试。",
  saveFailed: "角色信息保存失败。",
  deleteFailed: "删除失败，请稍后重试。",
  lookSaveFailed: "造型保存失败。",
  lookDeleteFailed: "造型删除失败，请稍后重试。",
  lastLookDeleteForbidden: "不能删除角色的最后一套造型。",
  referenceSaveFailed: "参考图元数据保存失败。",
  referenceDeleteFailed: "参考图删除失败，请稍后重试。",
  referenceActionFailed: "参考图状态更新失败，请稍后重试。",
  uploadFailed: "参考图上传失败，请检查文件格式和大小。",
  created: "角色已创建。",
  updated: "角色已更新。",
  deleted: "角色已删除。",
  lookCreated: "造型已创建。",
  lookUpdated: "造型已更新。",
  lookDeleted: "造型已删除。",
  defaultLookUpdated: "默认造型已更新。",
  referenceUploaded: "参考图已上传。",
  referenceUpdated: "参考图元数据已更新。",
  referenceDeleted: "参考图已删除。",
  primaryReferenceUpdated: "主图已更新。",
  identityAnchorUpdated: "身份基准状态已更新。",
  noDescription: "暂无说明",
  primaryReference: "主图",
  identityAnchor: "身份基准",
  notFoundTitle: "角色不存在或已被删除",
  analysis: "分析状态",
  cancel: "取消",
  confirmDelete: "确认删除",
  save: "保存",
  saving: "正在保存",
  uploading: "正在上传",
  deleting: "正在删除",
  noValue: "未填写",
  yes: "是",
  no: "否",
  deleteCharacterDescription: (name: string) =>
    `确定删除角色“${name}”吗？该角色下的造型、参考图和媒体文件记录都会一并删除。`,
  deleteLookDescription: (name: string) =>
    `确定删除造型“${name}”吗？该造型下的全部参考图都会删除；如果它是默认造型，后端会自动选择新的默认造型。`,
  deleteReferenceDescription: (name: string) =>
    `确定删除参考图“${name}”吗？原图和缩略图会在数据库删除成功后清理。`,
  fields: {
    name: "角色名称",
    aliases: "别名",
    roleType: "角色类型",
    description: "角色简介",
    appearanceDescription: "外貌描述",
    personalityDescription: "性格描述",
    promptIdentity: "身份提示词",
    lookName: "造型名称",
    lookDescription: "造型说明",
    costumeDescription: "服装描述",
    hairDescription: "发型描述",
    makeupDescription: "妆容描述",
    conditionDescription: "特殊状态",
    promptAppearance: "完整造型提示描述",
    file: "参考图片",
    originalFilename: "原始文件名",
    imageSize: "图片尺寸",
    fileType: "文件类型",
    fileSize: "文件大小",
    shotType: "景别",
    viewAngle: "视角",
    expression: "表情",
    customExpression: "自定义表情",
    poseType: "姿势",
    customPose: "自定义姿势",
    tags: "标签",
    referenceDescription: "参考图描述",
    notes: "备注",
    isPrimary: "主图状态",
    isIdentityAnchor: "身份基准状态"
  },
  placeholders: {
    name: "例如：林知夏",
    aliases: "可填写艺名、昵称或剧中别称",
    description: "简要描述角色关系、职业和剧情定位",
    appearance: "人物外貌、年龄感、体态、辨识特征",
    personality: "性格、行为习惯和情绪基调",
    promptIdentity: "用于后续生成时稳定身份的一段描述",
    lookName: "例如：通勤造型、夜戏造型",
    costume: "服装款式、材质、颜色和搭配",
    hair: "发型、发色、刘海或发饰",
    makeup: "妆容浓淡、唇色、眼妆等",
    condition: "例如：雨中、受伤、疲惫、宴会后",
    promptAppearance: "完整描述这套造型的外观特征",
    referenceTags: "用逗号分隔，例如：正面, 身份, 通勤",
    referenceDescription: "补充这张图的可用信息",
    notes: "仅用于制作管理的内部备注"
  },
  role: {
    protagonist: "主角",
    antagonist: "反派",
    supporting: "配角",
    extra: "群演",
    other: "其他"
  } satisfies Record<RoleType, string>,
  shotType: {
    unknown: "未知",
    face_closeup: "面部特写",
    closeup: "近景",
    upper_body: "上半身",
    half_body: "半身",
    three_quarter: "七分身",
    full_body: "全身"
  } satisfies Record<ShotType, string>,
  viewAngle: {
    unknown: "未知",
    front: "正面",
    left_45: "左 45 度",
    right_45: "右 45 度",
    left_profile: "左侧面",
    right_profile: "右侧面",
    back: "背面",
    high_angle: "俯视",
    low_angle: "仰视"
  } satisfies Record<ViewAngle, string>,
  expression: {
    unknown: "未知",
    neutral: "中性",
    happy: "开心",
    smile: "微笑",
    sad: "悲伤",
    angry: "愤怒",
    shocked: "震惊",
    fearful: "恐惧",
    crying: "哭泣",
    cold_smirk: "冷笑",
    serious: "严肃",
    custom: "自定义"
  } satisfies Record<Expression, string>,
  poseType: {
    unknown: "未知",
    standing: "站立",
    sitting: "坐姿",
    walking: "行走",
    looking_camera: "看镜头",
    looking_away: "看向别处",
    holding_object: "持物",
    custom: "自定义"
  } satisfies Record<PoseType, string>,
  analysisStatus: {
    not_analyzed: "尚未分析",
    pending: "分析中",
    completed: "分析完成",
    failed: "分析失败"
  } satisfies Record<AnalysisStatus, string>
};
